[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  path = "/ytify/streams/*"
  function = "ytify-proxy"

[[edge_functions]]
  path = "/test"
  function = "test"

[[redirects]]
  from = "/ytify/streams/*"
  to = "/.netlify/edge-functions/ytify-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/test"
  to = "/.netlify/edge-functions/test"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 