[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/ytify/streams/*"
  to = "/.netlify/edge-functions/ytify-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/test"
  to = "/.netlify/edge-functions/test"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 